# Generated by Django 5.0.1 on 2024-01-19 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('protection', models.CharField(choices=[('NONE', 'None'), ('HCAPTCHA', 'hCaptcha'), ('RECAPTCHA', 'Re-Captcha')], max_length=10)),
                ('protection_key', models.CharField(max_length=255, null=True)),
                ('notification', models.CharField(choices=[('NONE', 'None'), ('IMMEDIATE', 'Immediate'), ('DIGEST', 'Digest')], max_length=10)),
                ('digest_time', models.IntegerField(null=True)),
                ('digest_day_part', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_reset_token', models.CharField(max_length=255, null=True)),
                ('password_reset_token_created', models.DateTimeField(null=True)),
                ('two_factor_auth_token', models.CharField(max_length=255, null=True)),
                ('two_factor_auth_token_created', models.DateTimeField(null=True)),
                ('invite_token', models.CharField(max_length=255, null=True)),
                ('invite_token_created', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbox.form')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbox.form')),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('two_factor_type', models.CharField(choices=[('TOTP', 'Time-Based One Time Password'), ('SMS', 'SMS'), ('EMAIL', 'E-mail')], max_length=6)),
                ('target', models.CharField(max_length=255, null=True)),
                ('secret', models.CharField(max_length=255, null=True)),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
