# Generated by Django 5.0.1 on 2024-01-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbox', '0002_authsetting_teaminvite_twofactoroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsetting',
            name='invite_token_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='authsetting',
            name='password_reset_token_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='authsetting',
            name='two_factor_auth_token_created',
            field=models.DateTimeField(null=True),
        ),
    ]
