# Generated by Django 5.0.1 on 2024-01-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbox', '0002_twofactoroption_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactoroption',
            name='code',
        ),
    ]
