# Generated by Django 5.0.1 on 2024-01-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbox', '0004_alter_twofactoroption_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsetting',
            name='needs_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
