# Generated by Django 5.0.1 on 2024-01-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbox', '0005_authsetting_needs_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authsetting',
            name='invite_token',
        ),
        migrations.RemoveField(
            model_name='authsetting',
            name='invite_token_created',
        ),
    ]
