# Generated by Django 5.0.1 on 2024-02-15 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbox', '0006_remove_authsetting_invite_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='project',
        ),
        migrations.CreateModel(
            name='FormDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbox.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbox.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbox.form')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectNotification',
        ),
        migrations.DeleteModel(
            name='ProjectSubmission',
        ),
    ]
