# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dto.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class LoginResponse(betterproto.Message):
    state: "AuthenticationState" = betterproto.enum_field(1)
    password_reset_token: str = betterproto.string_field(2)
    two_factor_auth_token: str = betterproto.string_field(3)
    auth_token: str = betterproto.string_field(4)
    refresh_token: str = betterproto.string_field(5)


@dataclass
class GetUserResponse(betterproto.Message):
    username: str = betterproto.string_field(1)
    email: str = betterproto.string_field(2)


@dataclass
class CheckAvailabilityResponse(betterproto.Message):
    available: bool = betterproto.bool_field(1)


@dataclass
class ChangeUsernameResponse(betterproto.Message):
    state: "ChangeUsernameState" = betterproto.enum_field(1)


@dataclass
class ChangeEmailResponse(betterproto.Message):
    state: "ChangeEmailState" = betterproto.enum_field(1)


@dataclass
class ChangePasswordResponse(betterproto.Message):
    state: "ChangePasswordState" = betterproto.enum_field(1)


@dataclass
class TwoFactorOption(betterproto.Message):
    state: "TwoFactorSaveState" = betterproto.enum_field(1)
    id: int = betterproto.int32_field(2)
    nickname: str = betterproto.string_field(3)
    two_factor_type: "TwoFactorType" = betterproto.enum_field(4)
    target: str = betterproto.string_field(5)
    code: str = betterproto.string_field(6)


@dataclass
class MFAOption(betterproto.Message):
    id: int = betterproto.int32_field(1)
    nickname: str = betterproto.string_field(2)
    type: "TwoFactorType" = betterproto.enum_field(3)
    preview: str = betterproto.string_field(4)


@dataclass
class DeleteTwoFactorResponse(betterproto.Message):
    state: "DeleteTwoFactorState" = betterproto.enum_field(1)


@dataclass
class ApiUser(betterproto.Message):
    id: int = betterproto.int32_field(1)
    username: str = betterproto.string_field(2)
    email: str = betterproto.string_field(3)


@dataclass
class PageableApiUser(betterproto.Message):
    total: int = betterproto.int32_field(1)
    results: List["ApiUser"] = betterproto.message_field(2)


@dataclass
class ApiForm(betterproto.Message):
    id: int = betterproto.int32_field(1)
    name: str = betterproto.string_field(2)
    slug: str = betterproto.string_field(3)
    protection_type: "ProtectionType" = betterproto.enum_field(4)
    protection_key: str = betterproto.string_field(5)
    notification_type: "NotificationType" = betterproto.enum_field(6)
    digest_time: int = betterproto.int32_field(7)
    digest_day_part: "DayPart" = betterproto.enum_field(8)
    domains: List[str] = betterproto.string_field(9)
    notifications: List[str] = betterproto.string_field(10)


@dataclass
class PageableApiForm(betterproto.Message):
    total: int = betterproto.int32_field(1)
    results: List["ApiForm"] = betterproto.message_field(2)
